### PR TITLE
removed previous iterative rounding codes

### PR DESCRIPTION
**Pull request by komietty**
Removing the previous iterative rounding code in the `integrate.h` which is duplicated with `iterative_rounding.h`.

### CODE REVIEW

**Comment by komietty** [comment]
Sorry, this includes some setting file updates. I recreated another PR.

**Comment by avaxman** [comment]
Thank you for this. I have to think about it, but in fact this gets overridden by the upcoming (hopefully in two weeks) version of Directional where I totally removed the "optimization" and only left this code... in addition, the part that reduces the rank of C is vital nonetheless, and cannot be removed.

**Comment by avaxman** [comment]
You can check it out in the "remove-dependencies" branch, which is working up to integration including---currently working on the 505 meshing (which requires heavy code writing to supplement CGAL).

**Comment by komietty** [comment]
@avaxman Thank you for the reply! I'm glad to hear that this project will be upgraded. I checked the libigl-free branch and the codes in `integrate.h` which seems great. As for the rank reduction of the constraint matrix, I thought the same thing was done when creating CSmall matrix inside `SIInitialSolutionTraits::init()` (I have checked that the same matrix was generated), but you are right, it is better to have pre rank reduction beforehand.

**Pull request closed without merging**
